# install brew
which -s brew
if [[ $? != 0 ]] ; then
  echo "Installing Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "Homebrew already installed"
fi

# font
brew install --cask font-iosevka-nerd-font

# wezterm
which -s wezterm
if [[ $? != 0 ]] ; then
  echo "Installing wezterm"
  brew install wezterm
else
  echo "wezterm already installed"
fi

which -s stow
if [[ $? != 0 ]] ; then
  echo "Installing stow"
  brew install stow
else
  echo "stow already installed"
fi

# tiling window manager
which -s aerospace
if [[ $? != 0 ]] ; then
  echo "Installing aerospace"
  brew install --cask nikitabobko/tap/aerospace
else
  echo "aerospace already installed"
fi

which -s sketchybar
if [[ $? != 0 ]] ; then
  echo "Installing sketchybar"
  brew tap FelixKratz/formulae
  brew install sketchybar
  brew services start sketchybar
else
  echo "sketchybar already installed"
fi

cd ~/dotfiles

stow zshrc

cp misc/themes/oh-my-zsh/lambdim-zsh-theme/lambdim.zsh-theme omz-themes/.oh-my-zsh/custom/themes/
stow omz-themes

# macos tiling windows manager and bar
stow aerospace sketchybar

# editors
stow nvim idea doom

# bob, generated by:
# bob complete zsh > ~/zfunc/.zfunc/_bob
stow zfunc

# tmux
stow tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# terminal configs
stow wezterm kitty

# global git configs
stow git

# zsh plugins
git clone https://github.com/jeffreytse/zsh-vi-mode \
  ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-vi-mode
git clone https://github.com/zsh-users/zsh-autosuggestions \
  ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# wezterm terminfo
# https://wezfurlong.org/wezterm/faq.html?h=underline#how-do-i-enable-undercurl-curly-underlines
tempfile=$(mktemp) \
  && curl -o $tempfile https://raw.githubusercontent.com/wez/wezterm/master/termwiz/data/wezterm.terminfo \
  && tic -x -o ~/.terminfo $tempfile \
  && rm $tempfile
