ln -s ~/dotfiles/rasbian/.bashrc ~/.bashrc

mkdir ~/.config

# vim
ln -s ~/dotfiles/nvim ~/.config

# bob, generated by:
# bob complete zsh > ~/.zfunc/_bob
ln -s ~/dotfiles/.zfunc ~

# ctags
# ln -s ~/dotfiles/.ctags.d ~

# global git configs
ln -s ~/dotfiles/git ~/.config/
